// 98 validated puzzles — all verified by BFS with optimal paths of 2-5 steps.
// Daily rotation: epoch 2026-04-05 UTC, puzzleIndex = dayNumber % PUZZLES.length
const PUZZLES = [
  // --- Original candidates ---
  { start: "cold", end: "warm", hint: "Temperature", optimalSteps: 4 },
  { start: "love", end: "hate", hint: "Opposites", optimalSteps: 3 },
  { start: "head", end: "tail", hint: "Flip", optimalSteps: 5 },
  { start: "lost", end: "find", hint: "Seek", optimalSteps: 5 },
  { start: "wild", end: "calm", hint: "Zen", optimalSteps: 4 },
  { start: "word", end: "game", hint: "Meta", optimalSteps: 5 },
  { start: "read", end: "book", hint: "Library", optimalSteps: 5 },
  { start: "king", end: "fool", hint: "Shakespeare", optimalSteps: 5 },
  { start: "bone", end: "meat", hint: "Dinner", optimalSteps: 5 },
  { start: "ship", end: "boat", hint: "At Sea", optimalSteps: 5 },
  { start: "dark", end: "dawn", hint: "Nightfall", optimalSteps: 2 },
  { start: "bold", end: "meek", hint: "Courage", optimalSteps: 5 },
  { start: "fore", end: "back", hint: "Direction", optimalSteps: 4 },
  { start: "land", end: "sail", hint: "Voyage", optimalSteps: 3 },
  { start: "gold", end: "rust", hint: "Decay", optimalSteps: 5 },
  { start: "home", end: "road", hint: "Journey", optimalSteps: 5 },
  { start: "burn", end: "cool", hint: "Heat", optimalSteps: 5 },
  { start: "harm", end: "heal", hint: "Medicine", optimalSteps: 5 },
  { start: "lake", end: "pond", hint: "Water", optimalSteps: 5 },
  { start: "sand", end: "dust", hint: "Desert", optimalSteps: 5 },
  { start: "silk", end: "wool", hint: "Fabric", optimalSteps: 5 },
  { start: "cake", end: "diet", hint: "Temptation", optimalSteps: 5 },
  { start: "rock", end: "sand", hint: "Beach", optimalSteps: 4 },
  { start: "nest", end: "home", hint: "Shelter", optimalSteps: 5 },
  { start: "mare", end: "colt", hint: "Horses", optimalSteps: 4 },
  { start: "warm", end: "cool", hint: "Climate", optimalSteps: 5 },
  { start: "hate", end: "love", hint: "Reversal", optimalSteps: 3 },
  { start: "lock", end: "door", hint: "Security", optimalSteps: 4 },
  { start: "boat", end: "dock", hint: "Marina", optimalSteps: 5 },
  { start: "cold", end: "heat", hint: "Season", optimalSteps: 4 },
  { start: "card", end: "game", hint: "Casino", optimalSteps: 3 },
  { start: "milk", end: "meal", hint: "Morning", optimalSteps: 4 },
  { start: "song", end: "tune", hint: "Melody", optimalSteps: 4 },
  { start: "mail", end: "post", hint: "Delivery", optimalSteps: 5 },
  { start: "boot", end: "shoe", hint: "Footwear", optimalSteps: 3 },
  { start: "dime", end: "coin", hint: "Money", optimalSteps: 5 },
  { start: "mold", end: "rust", hint: "Aging", optimalSteps: 5 },
  { start: "wand", end: "wilt", hint: "Magic", optimalSteps: 3 },
  { start: "fork", end: "road", hint: "Crossroads", optimalSteps: 4 },
  { start: "core", end: "rind", hint: "Fruit", optimalSteps: 5 },
  { start: "bake", end: "cook", hint: "Oven", optimalSteps: 5 },
  { start: "rust", end: "gold", hint: "Alchemy", optimalSteps: 5 },
  { start: "haze", end: "mist", hint: "Morning Dew", optimalSteps: 5 },
  { start: "cape", end: "mask", hint: "Hero", optimalSteps: 4 },
  { start: "gulf", end: "cove", hint: "Coast", optimalSteps: 5 },
  { start: "gale", end: "wind", hint: "Storm", optimalSteps: 5 },
  { start: "silk", end: "lace", hint: "Elegant", optimalSteps: 4 },
  { start: "lime", end: "mint", hint: "Fresh", optimalSteps: 3 },
  { start: "peak", end: "base", hint: "Mountain", optimalSteps: 5 },
  { start: "foam", end: "wave", hint: "Surf", optimalSteps: 5 },
  { start: "soot", end: "coal", hint: "Chimney", optimalSteps: 4 },
  { start: "mead", end: "wine", hint: "Medieval", optimalSteps: 4 },
  { start: "dune", end: "sand", hint: "Sahara", optimalSteps: 3 },
  { start: "lair", end: "cave", hint: "Hidden", optimalSteps: 5 },
  { start: "cork", end: "wine", hint: "Bottle", optimalSteps: 4 },
  { start: "woke", end: "rise", hint: "Awaken", optimalSteps: 4 },
  // --- Additional validated pairs ---
  { start: "bear", end: "deer", hint: "Wildlife", optimalSteps: 2 },
  { start: "cast", end: "role", hint: "Theater", optimalSteps: 4 },
  { start: "lane", end: "road", hint: "Street", optimalSteps: 5 },
  { start: "base", end: "fort", hint: "Military", optimalSteps: 4 },
  { start: "east", end: "west", hint: "Compass", optimalSteps: 3 },
  { start: "melt", end: "cold", hint: "Winter", optimalSteps: 3 },
  { start: "hunt", end: "find", hint: "Search", optimalSteps: 3 },
  { start: "mist", end: "haze", hint: "Foggy", optimalSteps: 5 },
  { start: "bead", end: "ring", hint: "Jewelry", optimalSteps: 4 },
  { start: "meal", end: "wine", hint: "Feast", optimalSteps: 5 },
  { start: "goat", end: "wolf", hint: "Prey", optimalSteps: 5 },
  { start: "lore", end: "tale", hint: "Story", optimalSteps: 4 },
  { start: "grit", end: "sand", hint: "Rough", optimalSteps: 5 },
  { start: "tame", end: "wild", hint: "Safari", optimalSteps: 5 },
  { start: "dose", end: "cure", hint: "Remedy", optimalSteps: 4 },
  { start: "wage", end: "earn", hint: "Paycheck", optimalSteps: 3 },
  { start: "tide", end: "wave", hint: "Ocean", optimalSteps: 3 },
  { start: "duke", end: "king", hint: "Royalty", optimalSteps: 5 },
  { start: "fume", end: "rage", hint: "Anger", optimalSteps: 4 },
  { start: "coal", end: "gold", hint: "Treasure", optimalSteps: 4 },
  { start: "bolt", end: "lock", hint: "Secure", optimalSteps: 4 },
  { start: "vane", end: "wind", hint: "Rooftop", optimalSteps: 3 },
  { start: "reed", end: "pond", hint: "Wetland", optimalSteps: 3 },
  { start: "cork", end: "seal", hint: "Preserve", optimalSteps: 5 },
  { start: "sore", end: "well", hint: "Healing", optimalSteps: 5 },
  { start: "fold", end: "deal", hint: "Poker", optimalSteps: 5 },
  { start: "tomb", end: "bone", hint: "Ancient", optimalSteps: 3 },
  { start: "bale", end: "barn", hint: "Haystack", optimalSteps: 2 },
  { start: "fort", end: "moat", hint: "Castle", optimalSteps: 3 },
  { start: "helm", end: "mast", hint: "Nautical", optimalSteps: 5 },
  { start: "silt", end: "sand", hint: "Riverbed", optimalSteps: 4 },
  { start: "lure", end: "hook", hint: "Angler", optimalSteps: 5 },
  { start: "mead", end: "beer", hint: "Tavern", optimalSteps: 3 },
  { start: "well", end: "deep", hint: "Wishing", optimalSteps: 4 },
  { start: "yoke", end: "bond", hint: "Union", optimalSteps: 5 },
  { start: "coal", end: "soot", hint: "Fireplace", optimalSteps: 4 },
  { start: "mint", end: "gold", hint: "Treasury", optimalSteps: 4 },
  { start: "colt", end: "mare", hint: "Stable", optimalSteps: 4 },
  { start: "weed", end: "vine", hint: "Overgrown", optimalSteps: 5 },
  { start: "mane", end: "tail", hint: "Lion", optimalSteps: 4 },
  { start: "dusk", end: "moon", hint: "Evening", optimalSteps: 5 },
  { start: "lace", end: "silk", hint: "Luxury", optimalSteps: 4 },
];

const EPOCH = new Date("2026-04-05T00:00:00Z").getTime();

export function getDailyPuzzle() {
  const now = Date.now();
  const dayNumber = Math.floor((now - EPOCH) / 86400000);
  const idx = ((dayNumber % PUZZLES.length) + PUZZLES.length) % PUZZLES.length;
  return { ...PUZZLES[idx], idx, dayNumber };
}

export { PUZZLES };
